---
title: "Let's talk about Positron!"
subtitle: "Kolkata R User Group (Online)"
date: "2025/08/27"
author: "Saranjeet Kaur Bhogal"
institute: Imperial College London
format: 
  revealjs:
    incremental: true
    slide-number: true
    show-slide-number: all
    footer: "saranjeetkaur.github.io/intro_positron"
execute: 
  echo: false
  warning: false
  cache: true
  freeze: true
from: markdown+emoji
---

# What is Positron?

- Next-gen IDE for data science
- Was available for beta testing and has recently moved to stable release
- Fork of the open-source project that builds VS Code

# Who is the audience?

- Primarily R users
- Most experience with RStudio
- Maybe tried VS Code, Jupyter, etc.

# Ideology

- Polyglot (multilingual) IDE
- Support for both R and Python
- Unlike single-language IDEs (RStudio, MATLAB)
- Real-world projects often require different programming languages

# Familiarity

- Similar to RStudio (in layout - console, editor, help, plots)
- Based on VS Code OSS

# Thanks

- Julia Silge: talk link

# Resources

- Books, blogs, repo, website, talks, etc.

# Slides

- Slides made using [quarto](https://github.com/quarto-dev/quarto) in Positron

# Learning more

- About Positron: https://positron.posit.co

- talk link: saranjeetkaur.github.io/intro_positron/

- GitHub: SaranjeetKaur

- Email: kaur.saranjeet3\@gmail.com

# **Thank you!**